'use strict';

const TARGET = 1800;
const LOG_ROOM = '5ybwphczduwg';
const FOOD_ROOM = 'yve145gi1nxa';
const ETHERCALC = 'https://ethercalc.net';
const SYNC_MS = 15000;
const MEAL_ORDER = ['Mic dejun','Prânz','Cină','Gustare'];
const DEFAULT_FOODS = [
  ['Orez fiert',130,'Cereale'],['Paste fierte',158,'Cereale'],['Pâine integrală',247,'Panificație'],['Fulgi de ovăz',379,'Cereale'],
  ['Cartofi fierți',87,'Legume'],['Cartofi copți',93,'Legume'],['Cartofi prăjiți',312,'Fast food'],['Mămăligă',70,'Cereale'],
  ['Piept de pui gătit',165,'Carne'],['Pulpă de pui gătită',209,'Carne'],['Curcan gătit',135,'Carne'],['Vită slabă gătită',217,'Carne'],
  ['Somon gătit',206,'Pește'],['Ton în suc propriu',116,'Pește'],['Ou fiert',155,'Ouă'],['Șuncă',145,'Carne'],
  ['Lapte 1.5%',46,'Lactate'],['Iaurt grecesc 2%',73,'Lactate'],['Brânză telemea',280,'Lactate'],['Cașcaval',356,'Lactate'],
  ['Măr',52,'Fructe'],['Banană',89,'Fructe'],['Portocală',47,'Fructe'],['Căpșuni',32,'Fructe'],['Afine',57,'Fructe'],
  ['Roșii',18,'Legume'],['Castraveți',15,'Legume'],['Ardei gras',31,'Legume'],['Broccoli',34,'Legume'],['Morcov',41,'Legume'],
  ['Avocado',160,'Fructe'],['Nuci',654,'Nuci și semințe'],['Migdale',579,'Nuci și semințe'],['Unt de arahide',588,'Nuci și semințe'],
  ['Ulei de măsline',884,'Grăsimi'],['Ciocolată neagră',598,'Dulciuri'],['Înghețată',207,'Dulciuri'],['Pizza',266,'Fast food']
];

const state = { meals: [], foods: [], selectedDate: todayISO(), calendarMonth: new Date(), syncing: false, showAllFoods: false };
const $ = s => document.querySelector(s);
const el = {
  syncStatus:$('#syncStatus'), syncButton:$('#syncButton'), selectedDateLabel:$('#selectedDateLabel'), datePicker:$('#datePicker'), openDatePicker:$('#openDatePicker'), prevDay:$('#prevDay'), nextDay:$('#nextDay'),
  dailyCalories:$('#dailyCalories'), targetRing:$('#targetRing'), dayStatus:$('#dayStatus'), remainingText:$('#remainingText'), metricCalories:$('#metricCalories'), metricItems:$('#metricItems'), metricMeal:$('#metricMeal'), metricMealSub:$('#metricMealSub'), metricAverage:$('#metricAverage'),
  calendarTitle:$('#calendarTitle'), calendarGrid:$('#calendarGrid'), prevMonth:$('#prevMonth'), nextMonth:$('#nextMonth'), todayButton:$('#todayButton'), chart:$('#calorieChart'), mealGroups:$('#mealGroups'), emptyDiary:$('#emptyDiary'),
  mealDialog:$('#mealDialog'), mealForm:$('#mealForm'), mealId:$('#mealId'), mealFood:$('#mealFood'), mealGrams:$('#mealGrams'), mealType:$('#mealType'), mealNote:$('#mealNote'), mealPreview:$('#mealCaloriesPreview'), mealDialogTitle:$('#mealDialogTitle'),
  foodDialog:$('#foodDialog'), foodForm:$('#foodForm'), foodId:$('#foodId'), foodName:$('#foodName'), foodCalories:$('#foodCalories'), foodCategory:$('#foodCategory'), foodDialogTitle:$('#foodDialogTitle'), deleteFood:$('#deleteFood'), foodTable:$('#foodTable'), foodSearch:$('#foodSearch'), showAllFoods:$('#showAllFoods'), toast:$('#toast')
};

function todayISO(){const d=new Date();return localISO(d)}
function localISO(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function fromISO(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function addDays(iso,n){const d=fromISO(iso);d.setDate(d.getDate()+n);return localISO(d)}
function fmtDate(iso){const d=fromISO(iso);const today=todayISO();if(iso===today)return `Astăzi · ${d.toLocaleDateString('ro-RO',{day:'numeric',month:'long'})}`;return d.toLocaleDateString('ro-RO',{weekday:'long',day:'numeric',month:'long',year:d.getFullYear()!==new Date().getFullYear()?'numeric':undefined})}
function setSync(text,type=''){el.syncStatus.textContent=text;el.syncStatus.dataset.type=type}
function csvEscape(v){const s=String(v??'');return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function parseCsv(text){const rows=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')q=false;else field+=c}else if(c==='"')q=true;else if(c===','){row.push(field);field=''}else if(c==='\n'){row.push(field.replace(/\r$/,''));rows.push(row);row=[];field=''}else field+=c}if(field||row.length){row.push(field.replace(/\r$/,''));rows.push(row)}return rows}
function rowsToCsv(rows){return rows.map(r=>r.map(csvEscape).join(',')).join('\n')}
function roomUrl(room,write=false){return write?`${ETHERCALC}/_/${room}`:`${ETHERCALC}/_/${room}/csv?t=${Date.now()}`}
async function getCsv(room){const r=await fetch(roomUrl(room),{cache:'no-store'});if(!r.ok)throw new Error(`EtherCalc ${r.status}`);return r.text()}
async function putCsv(room,csv){const r=await fetch(roomUrl(room,true),{method:'PUT',headers:{'Content-Type':'text/csv;charset=UTF-8'},body:csv});if(!r.ok)throw new Error(`EtherCalc ${r.status}`)}

function parseFoods(csv){const rows=parseCsv(csv).filter(r=>r.some(Boolean));if(!rows.length)return[];const start=(rows[0][0]||'').toLowerCase().includes('id')?1:0;return rows.slice(start).map(r=>({id:r[0]||crypto.randomUUID(),name:r[1]||'',kcal100:Number(r[2])||0,category:r[3]||'',updatedAt:r[4]||''})).filter(f=>f.name)}
function foodsCsv(){return rowsToCsv([['id','name','kcal_per_100g','category','updated_at'],...state.foods.sort((a,b)=>a.name.localeCompare(b.name,'ro')).map(f=>[f.id,f.name,f.kcal100,f.category,f.updatedAt])])}
function parseMeals(csv){const rows=parseCsv(csv).filter(r=>r.some(Boolean));if(!rows.length)return[];const start=(rows[0][0]||'').toLowerCase().includes('id')?1:0;return rows.slice(start).map(r=>({id:r[0]||crypto.randomUUID(),date:r[1]||'',meal:r[2]||'Gustare',foodId:r[3]||'',foodName:r[4]||'',grams:Number(r[5])||0,kcal:Number(r[6])||0,note:r[7]||'',updatedAt:r[8]||''})).filter(x=>x.date&&x.foodName)}
function mealsCsv(){return rowsToCsv([['id','date','meal','food_id','food_name','grams','kcal','note','updated_at'],...state.meals.sort((a,b)=>(a.date+a.meal).localeCompare(b.date+b.meal)).map(m=>[m.id,m.date,m.meal,m.foodId,m.foodName,m.grams,m.kcal,m.note,m.updatedAt])])}

async function seedFoodsIfNeeded(){if(state.foods.length)return;const now=new Date().toISOString();state.foods=DEFAULT_FOODS.map(([name,kcal100,category])=>({id:crypto.randomUUID(),name,kcal100,category,updatedAt:now}));await putCsv(FOOD_ROOM,foodsCsv());showToast('Am adăugat lista implicită de alimente în EtherCalc.')}
async function syncAll({notify=false}={}){if(state.syncing)return;state.syncing=true;setSync('Se sincronizează…');try{const [foodCsv,mealCsv]=await Promise.all([getCsv(FOOD_ROOM),getCsv(LOG_ROOM)]);state.foods=parseFoods(foodCsv);state.meals=parseMeals(mealCsv);await seedFoodsIfNeeded();renderAll();setSync(`Sincronizat ${new Date().toLocaleTimeString('ro-RO',{hour:'2-digit',minute:'2-digit'})}`,'ok');if(notify)showToast('Date sincronizate.')}catch(e){console.error(e);setSync('Eroare de conectare','error');if(notify)showToast('Nu am putut sincroniza cu EtherCalc.')}finally{state.syncing=false}}
async function saveFoods(){setSync('Se salvează alimentele…');await putCsv(FOOD_ROOM,foodsCsv());setSync('Baza de alimente salvată','ok')}
async function saveMeals(){setSync('Se salvează jurnalul…');await putCsv(LOG_ROOM,mealsCsv());setSync('Jurnal salvat','ok')}

function mealsFor(date){return state.meals.filter(m=>m.date===date)}
function caloriesFor(date){return Math.round(mealsFor(date).reduce((s,m)=>s+m.kcal,0))}
function selectedFood(){return state.foods.find(f=>f.id===el.mealFood.value)}
function calcPreview(){const f=selectedFood(),g=Number(el.mealGrams.value)||0;el.mealPreview.textContent=f?Math.round(f.kcal100*g/100):0}
function renderFoodSelect(){const current=el.mealFood.value;el.mealFood.innerHTML='<option value="">— Alege alimentul —</option>';state.foods.slice().sort((a,b)=>a.name.localeCompare(b.name,'ro')).forEach(f=>{const o=document.createElement('option');o.value=f.id;o.textContent=`${f.name} · ${f.kcal100} kcal/100g`;el.mealFood.appendChild(o)});if([...el.mealFood.options].some(o=>o.value===current))el.mealFood.value=current;calcPreview()}

function renderSummary(){const list=mealsFor(state.selectedDate),total=caloriesFor(state.selectedDate),pct=Math.min(total/TARGET,1)*360;el.selectedDateLabel.textContent=fmtDate(state.selectedDate);el.datePicker.value=state.selectedDate;el.dailyCalories.textContent=total;el.targetRing.style.setProperty('--progress',`${pct}deg`);el.targetRing.classList.toggle('is-over',total>TARGET);el.dayStatus.textContent=total>TARGET?'Peste obiectiv':'În obiectiv';el.dayStatus.classList.toggle('is-over',total>TARGET);const diff=TARGET-total;el.remainingText.textContent=diff>=0?`Mai ai ${diff} kcal disponibile.`:`Ai depășit ținta cu ${Math.abs(diff)} kcal.`;el.metricCalories.textContent=total;el.metricItems.textContent=list.length;
 const byMeal=MEAL_ORDER.map(name=>[name,Math.round(list.filter(m=>m.meal===name).reduce((s,m)=>s+m.kcal,0))]).sort((a,b)=>b[1]-a[1]);if(byMeal[0][1]){el.metricMeal.textContent=byMeal[0][0];el.metricMealSub.textContent=`${byMeal[0][1]} kcal`}else{el.metricMeal.textContent='—';el.metricMealSub.textContent='fără înregistrări'}
 let sum=0;for(let i=0;i<7;i++)sum+=caloriesFor(addDays(state.selectedDate,-i));el.metricAverage.textContent=Math.round(sum/7)}

function renderDiary(){const list=mealsFor(state.selectedDate);el.mealGroups.innerHTML='';el.emptyDiary.hidden=!!list.length;if(!list.length)return;MEAL_ORDER.forEach(type=>{const items=list.filter(m=>m.meal===type);if(!items.length)return;const group=document.createElement('div');group.className='meal-group';const total=Math.round(items.reduce((s,m)=>s+m.kcal,0));group.innerHTML=`<div class="meal-group__title"><strong>${type}</strong><span>${total} kcal</span></div>`;items.sort((a,b)=>a.foodName.localeCompare(b.foodName,'ro')).forEach(m=>{const row=document.createElement('div');row.className='meal-item';row.innerHTML=`<div class="meal-item__name"><strong></strong><span></span></div><div class="meal-item__kcal">${Math.round(m.kcal)} kcal</div><div class="meal-item__actions"><button class="mini-button edit" title="Editează">✎</button><button class="mini-button del" title="Șterge">×</button></div>`;row.querySelector('strong').textContent=m.foodName;row.querySelector('.meal-item__name span').textContent=`${m.grams} g${m.note?` · ${m.note}`:''}`;row.querySelector('.edit').onclick=()=>openMeal(m.id);row.querySelector('.del').onclick=()=>deleteMeal(m.id);group.appendChild(row)});el.mealGroups.appendChild(group)})}

function renderCalendar(){const d=new Date(state.calendarMonth.getFullYear(),state.calendarMonth.getMonth(),1);el.calendarTitle.textContent=d.toLocaleDateString('ro-RO',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase());const y=d.getFullYear(),m=d.getMonth();const first=(d.getDay()+6)%7;const start=new Date(y,m,1-first);el.calendarGrid.innerHTML='';for(let i=0;i<42;i++){const day=new Date(start);day.setDate(start.getDate()+i);const iso=localISO(day),total=caloriesFor(iso);const b=document.createElement('button');b.type='button';b.className='calendar-day';if(day.getMonth()!==m)b.classList.add('is-outside');if(iso===state.selectedDate)b.classList.add('is-selected');if(total)b.classList.add('has-data');if(total>TARGET)b.classList.add('is-over');b.innerHTML=`<span class="calendar-day__number">${day.getDate()}</span><i class="calendar-day__dot"></i>${total?`<span class="calendar-day__kcal">${total} kcal</span>`:''}`;b.onclick=()=>selectDate(iso);el.calendarGrid.appendChild(b)}}

function renderFoods(){const q=el.foodSearch.value.trim().toLocaleLowerCase('ro-RO');let foods=state.foods.filter(f=>!q||`${f.name} ${f.category}`.toLocaleLowerCase('ro-RO').includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'ro'));if(!state.showAllFoods&&!q)foods=foods.slice(0,8);el.foodTable.innerHTML='';foods.forEach(f=>{const row=document.createElement('div');row.className='food-row';row.innerHTML='<div class="food-row__name"><strong></strong><span></span></div><div class="food-row__kcal"></div><button class="mini-button" title="Editează">✎</button>';row.querySelector('strong').textContent=f.name;row.querySelector('.food-row__name span').textContent=f.category||'Necategorizat';row.querySelector('.food-row__kcal').textContent=`${f.kcal100} kcal`;row.querySelector('button').onclick=()=>openFood(f.id);el.foodTable.appendChild(row)});el.showAllFoods.textContent=state.showAllFoods?'Arată mai puține':'Arată toate alimentele';el.showAllFoods.hidden=!!q||state.foods.length<=8}

function drawChart(){const canvas=el.chart,rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const W=rect.width,H=rect.height,pad={l:44,r:16,t:16,b:34};ctx.clearRect(0,0,W,H);const data=[];for(let i=13;i>=0;i--){const date=addDays(state.selectedDate,-i);data.push({date,value:caloriesFor(date)})}const max=Math.max(2200,...data.map(d=>d.value));const chartH=H-pad.t-pad.b,chartW=W-pad.l-pad.r;ctx.font='11px system-ui';ctx.textAlign='right';ctx.textBaseline='middle';ctx.fillStyle='#879089';ctx.strokeStyle='#e8ece8';ctx.lineWidth=1;[0,600,1200,1800,2400].filter(v=>v<=max+200).forEach(v=>{const y=pad.t+chartH-(v/max)*chartH;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(W-pad.r,y);ctx.stroke();ctx.fillText(v,pad.l-8,y)});const targetY=pad.t+chartH-(TARGET/max)*chartH;ctx.save();ctx.strokeStyle='#d77a35';ctx.setLineDash([6,5]);ctx.beginPath();ctx.moveTo(pad.l,targetY);ctx.lineTo(W-pad.r,targetY);ctx.stroke();ctx.restore();ctx.fillStyle='#b86c32';ctx.textAlign='left';ctx.fillText('1800',pad.l+5,targetY-8);const gap=Math.max(4,chartW/data.length*.18),bw=(chartW/data.length)-gap;data.forEach((d,i)=>{const x=pad.l+i*(chartW/data.length)+gap/2,h=(d.value/max)*chartH,y=pad.t+chartH-h;ctx.fillStyle=d.value>TARGET?'#d77a35':'#4f8b69';ctx.beginPath();roundRect(ctx,x,y,bw,Math.max(h,2),5);ctx.fill();if(i%2===1||W<520)return;ctx.fillStyle='#879089';ctx.textAlign='center';ctx.textBaseline='top';ctx.fillText(fromISO(d.date).getDate(),x+bw/2,H-pad.b+9)})}
function roundRect(ctx,x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function renderAll(){renderFoodSelect();renderSummary();renderDiary();renderCalendar();renderFoods();requestAnimationFrame(drawChart)}

function selectDate(iso){state.selectedDate=iso;const d=fromISO(iso);state.calendarMonth=new Date(d.getFullYear(),d.getMonth(),1);renderAll()}
function openMeal(id=''){el.mealForm.reset();el.mealId.value='';el.mealGrams.value=100;el.mealDialogTitle.textContent='Adaugă aliment';renderFoodSelect();if(id){const m=state.meals.find(x=>x.id===id);if(!m)return;el.mealId.value=m.id;el.mealFood.value=m.foodId;el.mealGrams.value=m.grams;el.mealType.value=m.meal;el.mealNote.value=m.note;el.mealDialogTitle.textContent='Editează aliment'}calcPreview();el.mealDialog.showModal()}
function openFood(id=''){el.foodForm.reset();el.foodId.value='';el.foodDialogTitle.textContent='Adaugă aliment';el.deleteFood.hidden=true;if(id){const f=state.foods.find(x=>x.id===id);if(!f)return;el.foodId.value=f.id;el.foodName.value=f.name;el.foodCalories.value=f.kcal100;el.foodCategory.value=f.category;el.foodDialogTitle.textContent='Editează aliment';el.deleteFood.hidden=false}el.foodDialog.showModal()}
async function deleteMeal(id){state.meals=state.meals.filter(m=>m.id!==id);renderAll();try{await saveMeals();showToast('Înregistrare ștearsă.')}catch(e){console.error(e);showToast('Ștergerea nu a putut fi salvată.')}}
async function handleMealSubmit(e){e.preventDefault();const f=selectedFood(),grams=Number(el.mealGrams.value);if(!f||!grams||grams<1){showToast('Alege alimentul și introdu cantitatea.');return}const id=el.mealId.value||crypto.randomUUID(),existing=state.meals.find(m=>m.id===id),record={id,date:existing?.date||state.selectedDate,meal:el.mealType.value,foodId:f.id,foodName:f.name,grams,kcal:Math.round(f.kcal100*grams/100),note:el.mealNote.value.trim(),updatedAt:new Date().toISOString()};state.meals=existing?state.meals.map(m=>m.id===id?record:m):[...state.meals,record];el.mealDialog.close();renderAll();try{await saveMeals();showToast(existing?'Înregistrare actualizată.':'Aliment adăugat.')}catch(err){console.error(err);showToast('Salvarea în EtherCalc a eșuat.')}}
async function handleFoodSubmit(e){e.preventDefault();const name=el.foodName.value.trim(),kcal=Number(el.foodCalories.value);if(!name||!Number.isFinite(kcal)||kcal<0){showToast('Completează denumirea și caloriile.');return}const id=el.foodId.value||crypto.randomUUID(),existing=state.foods.find(f=>f.id===id),record={id,name,kcal100:Math.round(kcal),category:el.foodCategory.value.trim(),updatedAt:new Date().toISOString()};state.foods=existing?state.foods.map(f=>f.id===id?record:f):[...state.foods,record];el.foodDialog.close();renderAll();try{await saveFoods();showToast(existing?'Aliment actualizat în mapare.':'Aliment adăugat în mapare.')}catch(err){console.error(err);showToast('Maparea nu a putut fi salvată.')}}
async function handleDeleteFood(){const id=el.foodId.value,f=state.foods.find(x=>x.id===id);if(!f)return;if(state.meals.some(m=>m.foodId===id)){showToast('Alimentul este folosit în jurnal. Îl poți edita, dar nu șterge.');return}state.foods=state.foods.filter(x=>x.id!==id);el.foodDialog.close();renderAll();try{await saveFoods();showToast('Aliment șters din mapare.')}catch(err){console.error(err);showToast('Ștergerea nu a putut fi salvată.')}}
let toastTimer;function showToast(msg){clearTimeout(toastTimer);el.toast.textContent=msg;el.toast.classList.add('show');toastTimer=setTimeout(()=>el.toast.classList.remove('show'),2800)}

$('#openMealDialog').onclick=()=>openMeal();$('#openMealDialog2').onclick=()=>openMeal();$('#emptyAdd').onclick=()=>openMeal();$('#closeMealDialog').onclick=()=>el.mealDialog.close();$('#cancelMeal').onclick=()=>el.mealDialog.close();el.mealForm.addEventListener('submit',handleMealSubmit);el.mealFood.addEventListener('change',calcPreview);el.mealGrams.addEventListener('input',calcPreview);
$('#openFoodDialog').onclick=()=>openFood();$('#closeFoodDialog').onclick=()=>el.foodDialog.close();$('#cancelFood').onclick=()=>el.foodDialog.close();el.foodForm.addEventListener('submit',handleFoodSubmit);el.deleteFood.onclick=handleDeleteFood;el.foodSearch.addEventListener('input',renderFoods);el.showAllFoods.onclick=()=>{state.showAllFoods=!state.showAllFoods;renderFoods()};
el.syncButton.onclick=()=>syncAll({notify:true});el.prevDay.onclick=()=>selectDate(addDays(state.selectedDate,-1));el.nextDay.onclick=()=>selectDate(addDays(state.selectedDate,1));el.openDatePicker.onclick=()=>{try{el.datePicker.showPicker()}catch(_){el.datePicker.click()}};el.datePicker.addEventListener('change',()=>el.datePicker.value&&selectDate(el.datePicker.value));el.todayButton.onclick=()=>selectDate(todayISO());el.prevMonth.onclick=()=>{state.calendarMonth=new Date(state.calendarMonth.getFullYear(),state.calendarMonth.getMonth()-1,1);renderCalendar()};el.nextMonth.onclick=()=>{state.calendarMonth=new Date(state.calendarMonth.getFullYear(),state.calendarMonth.getMonth()+1,1);renderCalendar()};
window.addEventListener('resize',()=>requestAnimationFrame(drawChart));document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncAll()});window.addEventListener('online',()=>syncAll({notify:true}));setInterval(()=>{if(!document.hidden)syncAll()},SYNC_MS);
renderAll();syncAll();
